name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run
      id: run
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Run
        setup-command: ''
        command: bash test.sh
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        RUN_RESULTS: "${{steps.run.outputs.result}}"
      with:
        runners: run
